# Generated by Django 3.2.6 on 2021-08-26 17:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_number', models.IntegerField(default=-1)),
                ('customer_name', models.TextField(default='')),
                ('customer_email', models.TextField(default='')),
                ('phone_number', models.TextField(default='')),
                ('number_of_guests', models.IntegerField(default=-1)),
                ('message', models.TextField(default='')),
                ('reservation_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('reserved_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('cancelled', models.BooleanField(default=False)),
            ],
        ),
    ]
